apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
namespace: pythonapiapp
  name: gp3
  annotation:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
parameters:
  csi.storage.k8s.io/fstype: ext4
  type: gp3
allowVolumeExpansion: true
