apiVersion: v1
kind: Service
metadata:
  name: pythonapi-service
  namespace: pythonapiapp
spec:
  selector:
    app: pythonapi
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP